baseurl = "/"
languageCode = "fr-be"
languageLang = "fr"
title = "logCiCa"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[caches]
  [caches.getcsv]
    maxAge = 0
  [caches.getjson]
    maxAge = 0
